// Generated by CoffeeScript 1.12.7
(function() {
  var Controller, DATA;

  Controller = (function() {
    function Controller() {}

    Controller.init = function() {
      return $((function(_this) {
        return function() {
          return _this.change_item_type();
        };
      })(this));
    };

    Controller.change_item_type = function() {
      var $tr, i, option_name, ref, results;
      ref = DATA.weapon;
      results = [];
      for (i in ref) {
        option_name = ref[i];
        $tr = $('<tr/>');
        $tr.append($("<td>" + option_name + "</td>"));
        $tr.append($("<td><input class='radio_red' id='option_" + i + "_need' name='option_" + i + "' value='need' type='radio'/><label for='option_" + i + "_need'/></td>"));
        $tr.append($("<td><input checked='checked' class='radio_red' id='option_" + i + "_ok' name='option_" + i + "' value='ok' type='radio'/><label for='option_" + i + "_ok'/></td>"));
        $tr.append($("<td><input class='radio_red' id='option_" + i + "_ng' name='option_" + i + "' value='ng' type='radio'/><label for='option_" + i + "_ng'/></td>"));
        results.push($('table#option_selector').append($tr));
      }
      return results;
    };

    return Controller;

  })();

  Controller.init();

  DATA = {
    weapon: ['攻撃速度増加率', 'HP吸収率', '物理攻撃力', '魔法攻撃力', 'クリティカル', 'クリティカルダメージ増加率', '防御無視ダメージ', '命中', '貫通', 'アデナ獲得量増加率', '経験値獲得量増加率'],
    head: ['HP吸収率', '物理防御力', '魔法防御力', '状態異常抵抗率', '最大HP', '最大MP', 'HP回復量', 'MP回復量', '固定ダメージ減少', '回避', '貫通', 'アデナ獲得量増加率', '経験値獲得量増加率']
  };

}).call(this);
